const menu=document.querySelector('.menu');const nav=document.querySelector('.site-header nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'✕':'☰'});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰'}));const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

const activityCards=[...document.querySelectorAll('[data-github]')];
const relativeTime=value=>{const seconds=Math.max(1,Math.floor((Date.now()-new Date(value).getTime())/1000));const units=[['year',31536000],['month',2592000],['day',86400],['hour',3600],['minute',60]];for(const [name,size]of units){const amount=Math.floor(seconds/size);if(amount>=1)return `Updated ${amount} ${name}${amount>1?'s':''} ago`}return 'Updated just now'};
if(activityCards.length){Promise.allSettled(activityCards.map(async card=>{const repo=card.dataset.github;const response=await fetch(`https://api.github.com/repos/${repo}`,{headers:{Accept:'application/vnd.github+json'}});if(!response.ok)throw new Error('GitHub metadata unavailable');const data=await response.json();const time=card.querySelector('.delivery-status time');if(time){time.textContent=relativeTime(data.pushed_at||data.updated_at);time.dateTime=data.pushed_at||data.updated_at;time.title=`Latest public repository activity: ${new Date(data.pushed_at||data.updated_at).toLocaleString()}`}}));}

(()=>{const grid=document.querySelector('.repo-grid');if(!grid)return;const combined=[...grid.querySelectorAll('.repo-card')].find(c=>{const h=c.querySelector('h3');return h&&h.textContent.includes('MEP Scanner + HIS Bill Scanner')});if(!combined)return;const make=(n,label,title,status,desc,tags,links)=>{const el=document.createElement('article');el.className='repo-card reveal visible';el.innerHTML=`<div class="repo-top"><span>${n} · ${label}</span><i>${status}</i></div><h3>${title}</h3><p>${desc}</p><div class="repo-tech">${tags.map(t=>`<b>${t}</b>`).join('')}</div><div class="dual-links">${links.map(([text,url])=>`<a href="${url}" target="_blank" rel="noreferrer">${text} ↗</a>`).join('')}</div>`;return el};const bill=make('04','DOCUMENT AI','HIS Bill Scanner','Live','Privacy-first browser OCR that converts invoices and receipts into structured financial data with review and CSV export.',['OCR','Tesseract.js','React','TypeScript'],[['Open scanner','https://his-bill-scanner.neat-grove-8624.chatgpt.site/'],['Source','https://github.com/safdar404/HIS-Bill-Scanner']]);const mep=make('05','ENGINEERING AI','MEP Drawing Scanner','Live','AI-assisted engineering drawing OCR that extracts MEP components, dimensions and airflow with confidence-based QA and Excel reporting.',['Python','EasyOCR','OpenCV','Streamlit'],[['Open scanner','https://mep-scanner-system.neat-grove-8624.chatgpt.site/'],['Source','https://github.com/safdar404/HIS-MEP-Scanner-System.']]);combined.replaceWith(bill,mep);})();

(()=>{const grid=document.querySelector('.repo-grid');if(!grid)return;const el=document.createElement('article');el.className='repo-card reveal visible';el.innerHTML=`<div class="repo-top"><span>NEW · GEOAI / SITE INTELLIGENCE</span><i>3 apps</i></div><h3>GeoAI Site Intelligence Suite</h3><p>Three AI/GeoAI geospatial decision-support applications: MERIDIAN PRO for site suitability, GEOSENTINEL PRO for flood-mitigation siting, and SOLARIS PRO for utility-scale solar site selection.</p><div class="repo-tech"><b>Python</b><b>AI/ML</b><b>GeoAI</b><b>GIS</b><b>Leaflet</b><b>MCDA</b></div><div class="dual-links"><a href="geoai-site-intelligence/">Open project ↗</a><a href="https://github.com/safdar404/safdar404.github.io/tree/main/geoai-site-intelligence" target="_blank" rel="noreferrer">Repository ↗</a></div>`;grid.prepend(el);})();

(()=>{const grid=document.querySelector('.repo-grid');if(!grid||grid.querySelector('[data-project="ai-healthassist"]'))return;const el=document.createElement('article');el.className='repo-card reveal visible';el.dataset.project='ai-healthassist';el.innerHTML=`<div class="repo-top"><span>NEW · HEALTHCARE AI / DECISION SUPPORT</span><i>Live</i></div><h3>AI-HealthAssist</h3><p>AI-powered healthcare decision-support and triage application for structured health information, risk awareness and escalation-oriented guidance.</p><div class="repo-tech"><b>AI/ML</b><b>Python</b><b>LLM</b><b>Healthcare AI</b><b>Triage</b></div><div class="dual-links"><a href="https://ai-healthassist.ai.studio/" target="_blank" rel="noreferrer">Open live application ↗</a><a href="ai-healthassist.html">Project details ↗</a><a href="https://github.com/safdar404/HIS-AI-HealthAssist" target="_blank" rel="noreferrer">Source ↗</a></div>`;grid.prepend(el);})();