const buttons=[...document.querySelectorAll('.tabs button')];const projects=[...document.querySelectorAll('.project')];buttons.forEach(button=>button.addEventListener('click',()=>{buttons.forEach(b=>b.classList.remove('active'));projects.forEach(p=>p.classList.remove('active'));button.classList.add('active');document.getElementById(button.dataset.tab).classList.add('active');history.replaceState(null,'',`#${button.dataset.tab}`);window.scrollTo({top:document.querySelector('.tabs').offsetTop-70,behavior:'smooth'})}));
const ink='#dceef7',grid='#31506755',cyan='#22d9ef',lime='#9ee94f',gold='#ffc65b',purple='#a77bff',red='#ff5f79';Chart.defaults.color=ink;Chart.defaults.font.family='Manrope';
const base={responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{boxWidth:10,usePointStyle:true}},tooltip:{backgroundColor:'#06111d',borderColor:'#3f7087',borderWidth:1}},scales:{x:{grid:{color:grid}},y:{grid:{color:grid}}}};
function bar(id,labels,datasets,y={}){new Chart(document.getElementById(id),{type:'bar',data:{labels,datasets},options:{...base,scales:{x:{grid:{display:false}},y:{grid:{color:grid},...y}}}})}
function line(id,labels,datasets,y={}){new Chart(document.getElementById(id),{type:'line',data:{labels,datasets},options:{...base,scales:{x:{grid:{display:false}},y:{grid:{color:grid},...y}}}})}
bar('q1Models',['Soft Voting','Random Forest','Logistic','Gradient Boost','SVM'],[{label:'ROC-AUC',data:[0.9286,0.9265,0.9223,0.9176,0.9119],backgroundColor:[lime,cyan,gold,purple,red]}],{min:.88,max:.95});
line('q1Clusters',['K=2','K=3','K=4','K=5','K=6'],[{label:'Silhouette score',data:[.1391,.1761,.1901,.2133,.1880],borderColor:cyan,backgroundColor:'#22d9ef44',pointBackgroundColor:[cyan,cyan,cyan,lime,cyan],pointRadius:6,fill:true,tension:.28}],{min:.1,max:.24});
bar('q2Models',['Soft Voting','Random Forest','Gradient Boost','Logistic'],[{label:'Accuracy',data:[.9458,.9524,.9471,.9365],backgroundColor:cyan},{label:'ROC-AUC',data:[.9757,.9714,.9713,.9683],backgroundColor:lime}],{min:.9,max:1});
bar('q2Beds',['Voting','Gradient Boost','Random Forest'],[{label:'RMSE (beds)',data:[115.03,117.68,119.47],backgroundColor:[lime,gold,cyan]}],{min:100,max:125});
bar('q3Mae',['Previous Close','LSTM','GRU','SimpleRNN'],[{label:'Test MAE (USD)',data:[4.4324,4.4322,4.4360,4.5048],backgroundColor:[gold,lime,cyan,purple]}],{min:4.35,max:4.55});
bar('q3Direction',['LSTM','GRU','SimpleRNN'],[{label:'Directional accuracy (%)',data:[52.47,51.62,50.34],backgroundColor:[lime,cyan,purple]}],{min:45,max:55});
bar('q4Mae',['LSTM','GRU','SimpleRNN','Seasonal Baseline'],[{label:'MAE',data:[4.96,4.98,5.73,7.70],backgroundColor:[lime,cyan,purple,gold]}],{min:0,max:9});
line('q4Forecast',['Apr 2026','May 2026','Jun 2026'],[{label:'Ensemble authorization count',data:[28,28,27],borderColor:lime,backgroundColor:'#9ee94f44',pointBackgroundColor:gold,pointRadius:7,fill:true,tension:.2}],{min:20,max:32});
const initial=location.hash.slice(1);if(initial&&document.getElementById(initial)){document.querySelector(`[data-tab="${initial}"]`)?.click()}
